import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className='container contain-content px-5 md:px-10'>
            <header>
                <nav>
                    
                </nav>
            </header>
            {/*{children}*/}
        </body>
    </html>
  );
}
